name: planner_app
description: Thin Notechondria app entrypoint for Notechondria Planner.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  notechondria_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
